.gitignore, DSL/Resql/testing.sql, DSL/Ruuter/GET/testing.yml, README.md, docker-compose.yml
Initial setup for developers
Includes a testing endpoint
=> 20-docker-compose

DSL/Resql/csa-avg-chat-time.sql, DSL/Resql/csa-avg-present-number.sql, DSL/Resql/csa-avg-time-picking-up-chats.sql, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/AdvisorsPage.tsx
=> 64-BUG-CSA's-Advisors-Page

GUI/.env.development, GUI/package.json, GUI/src/components/services/auth.ts, GUI/vite.config.ts, docker-compose.yml
- Adding auth api file
- Added REACT_APP_APP_PORT to env variable, default value set to 3001
- Vite.config port is now can be changed with this value
=> #83 Apply header and navigation menu

DSL/Resql/byk-avg-intents.sql, DSL/Resql/byk-avg-response-speed.sql, DSL/Resql/byk-intents-count.sql, DSL/Resql/byk-pct-correctly-understood.sql, DSL/Resql/chat-avg-num-of-messages.sql, DSL/Resql/chat-cif-long-waiting-time.sql, DSL/Resql/chat-count-only-chatbot.sql, DSL/Resql/chat-count-with-csa.sql, DSL/Resql/chat-idle-count.sql, DSL/Resql/get-chat-count-csa.sql, GUI/src/components/BarGraph/index.tsx, GUI/src/components/LineGraph/index.tsx, GUI/src/components/MetricsCharts/index.tsx, GUI/src/components/PieGraph/index.tsx, GUI/src/util/api-response-handler.tsx
- https://github.com/buerokratt/Analytics-Module/issues/7#issuecomment-1689899720
- https://github.com/buerokratt/Analytics-Module/issues/7#issuecomment-1688012532
- https://github.com/buerokratt/Analytics-Module/issues/7#issuecomment-1689369921
- https://github.com/buerokratt/Analytics-Module/issues/92
- https://github.com/buerokratt/Analytics-Module/issues/91
=> Bug Metrics and graphics under menu button Vestlused (chats)

GUI/src/components/BarGraph/index.tsx, GUI/src/components/LineGraph/index.tsx, GUI/src/components/PieGraph/index.tsx
Bugs Addressed: 
- https://github.com/buerokratt/Analytics-Module/issues/103#issuecomment-1715806102
- https://github.com/buerokratt/Analytics-Module/issues/103#issuecomment-1715820196
=> Bug Fixes to the Chats' page

DSL/Resql/csa-avg-chat-time.sql, DSL/Resql/csa-avg-time-picking-up-chats.sql, DSL/Resql/csa-chat-forwards.sql, DSL/Resql/csa-chats-count.sql, GUI/src/components/BarGraph/index.tsx, GUI/src/components/ChartToolTip/index.tsx, GUI/src/components/LineGraph/index.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/AdvisorsPage.tsx
- https://github.com/buerokratt/Analytics-Module/issues/112
=> Bug Fixes to Advisors Page

DSL/Resql/feedback-chats-with-negative-feedback.sql, GUI/src/components/BarGraph/index.tsx, GUI/src/components/ChartToolTip/index.tsx, GUI/src/components/LineGraph/index.tsx, GUI/src/pages/FeedbackPage.tsx
- https://github.com/buerokratt/Analytics-Module/issues/104#issuecomment-1724942124
=> Bug Fixes To Feedback Page

GUI/src/index.tsx
- Updated sse get all active chats endpoint to accept text/event-stream
- Added return statements to index.tsx
=> Updated sse get all chats, added return statements

GUI/Dockerfile.dev, GUI/src/pages/ReportsPage.tsx
- https://github.com/buerokratt/Analytics-Module/issues/3#issuecomment-1807639896
=> Bug Publish data in Open Data Portal

DSL/Ruuter/GET/overview/metrics.yml, GUI/src/components/overview/MainMetricsArea/index.tsx, GUI/src/pages/OverviewPage.tsx, GUI/src/resources/api-constants.ts, docker-compose.yml
- https://github.com/buerokratt/Analytics-Module/issues/2#issuecomment-1820885801
=> Bug Overview Metrics

docs/OpenAPI/openApiSpec.yml
OpenAPI 3.0.3 specification for the API endpoints of Buerokratt Analytics module based on the DSL ruuter files.
=> OpenAPI 3.0.3 specification for Analytics module API endpoints

GUI/package.json, GUI/src/components/MetricsCharts/index.tsx
Tasks Related:
- https://github.com/buerokratt/Analytics-Module/issues/78
=> Modify CSV Date Format

.github/dependabot.yml, GUI/package.json, GUI/src/components/Layout/index.tsx, README.md
- Apply header as npm package
- Updated readme
- Updated layout
- Added dependabot script
Related [task](https://github.com/buerokratt/Buerokratt-Chatbot/issues/360)
=> Apply header as npm package

.github/dependabot.yml, GUI/Dockerfile.dev, GUI/package.json, GUI/src/components/Layout/index.tsx, GUI/tsconfig.base.json, README.md
- Removed old header/menu package from project
- Updated layout
- Updated package json
- Updated readme
- Updated dependabot
Related [task](https://github.com/buerokratt/Buerokratt-Chatbot/issues/361).
=> Apply menu as npm package

GUI/src/App.tsx
=> Hot Fix User Info

DSL/Resql/feedback-chats-with-negative-feedback.sql, DSL/Ruuter/POST/feedback/chats-with-negative-feedback.yml, GUI/src/pages/FeedbackPage.tsx
- https://github.com/buerokratt/Analytics-Module/issues/104#issuecomment-1888759450
=> Fixed Negative Feedback Bug

GUI/src/RootComponent.tsx
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/8#issuecomment-1935737095
=> Removed Burokratt Page (To Be Released in Version 2.1 or later)

DSL/Resql/overview-avg-chats-no-csa.sql, DSL/Resql/overview-avg-chats.sql
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/77
=> Fix request - Metrics visualization in Overview

GUI/src/pages/ReportsPage.tsx
Related Bugs:
- https://github.com/buerokratt/Analytics-Module/issues/3#issuecomment-1940621777
=> Hot Fix ODP Download

DSL/Resql/feedback-chats-with-negative-feedback.sql, DSL/Resql/feedback-csa-chats-feedback-nps.sql, DSL/Resql/feedback-selected-csa-feedback-nps.sql, GUI/src/components/FormElements/FormDatepicker/index.tsx
Related Bugs:
- https://github.com/buerokratt/Analytics-Module/issues/9#issuecomment-1938372952
- https://github.com/buerokratt/Analytics-Module/issues/9#issuecomment-1938402643
=> Hot Fix Feedback Queries

DSL/Resql/feedback-chats-with-negative-feedback.sql
- Fixed Negative Chats Duplication
Related Bugs
- https://github.com/buerokratt/Analytics-Module/issues/9#issuecomment-1946013603
=> Hot Fix Negative Feedback Chats Duplication

DSL/Resql/feedback-chats-with-negative-feedback.sql, GUI/src/components/ChatsTable/index.tsx
Related Bugs:
- https://github.com/buerokratt/Analytics-Module/issues/104#issuecomment-1963661319
=> Hot Fix Ended Chat Dates

DSL/Resql/chat-cif-all-csas-away.sql, DSL/Resql/chat-cif-long-waiting-time.sql, DSL/Resql/chat-cif-outside-working-hours.sql, DSL/Resql/chat-cif-total.sql
Related bug:
- https://github.com/buerokratt/Analytics-Module/issues/139#issuecomment-1978632902
=> Corrections to queries related to metric Contact Information provided

DSL/Resql/chat-cif-all-csas-away.sql, DSL/Resql/chat-cif-long-waiting-time.sql, DSL/Resql/chat-cif-outside-working-hours.sql, DSL/Resql/chat-cif-total.sql
Related to:
- https://github.com/buerokratt/Analytics-Module/issues/139#issuecomment-1993811569
=> Hotfix for Contact Information Provided metrics issue

DSL/Ruuter/POST/login-user.yml
Related Task:
- https://github.com/buerokratt/Test-Driven-Development/issues/1
=> Secure Cookies

DSL/Ruuter/GET/.guard, DSL/Ruuter/GET/negative-feedback.yml, DSL/Ruuter/GET/overview/preferences.yml, DSL/Ruuter/POST/.guard, DSL/Ruuter/POST/overview/preferences.yml, DSL/Ruuter/TEMPLATES/check-user-authority.yml
Related to:
- https://github.com/buerokratt/Buerokratt-DSL/issues/5
=> Refactor accessing Ruuter DSLs

GUI/.env.development, GUI/index.html, GUI/vite.config.ts, README.md, docker-compose.yml
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/542
=> Apply CSP Restrictions

DSL/Ruuter/GET/metrics/intents.yml, DSL/Ruuter/GET/overview/preferences.yml, DSL/Ruuter/POST/auth/.guard, DSL/Ruuter/POST/auth/login.yml, GUI/src/pages/ReportsPage.tsx, GUI/vite.config.ts, README.md
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/552
=> Checking DSL's

DSL/Liquibase/changelog/1715345741-create_db_indexes.sql, DSL/Resql/csa-chat-forwards.sql
Related to:
- https://github.com/buerokratt/Analytics-Module/issues/213
=> Refactor `csa-chat-forwards.sql` Postgres query

DSL/Liquibase/changelog/1715345741-create_db_indexes.sql, DSL/Resql/feedback-chats-with-negative-feedback.sql
Related to:
- https://github.com/buerokratt/Analytics-Module/issues/214
=> Refactor `feedback-chats-with-negative-feedback.sql` Postgres query

DSL/Resql/get-scheduled-report.sql, DSL/Resql/get-scheduled-reports.sql
=> Refactor all Analytics Module's Postgres queries to replace `SELECT *` with `SELECT {field_name}`

GUI/Dockerfile, GUI/Dockerfile.dev, GUI/nginx/http-nginx.conf, GUI/nginx/https-nginx.conf, GUI/nginx/nginx.conf, docker-compose.yml
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/236
=> Added Image User & Ngnix

GUI/src/components/ChartToolTip/index.tsx, GUI/src/components/PercentageToolTip/index.tsx, GUI/src/components/PieGraph/PieCharLegends.tsx, GUI/src/components/PieGraph/index.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/BurokrattPage/data.tsx, GUI/src/pages/ChatsPage/data.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/util/api-response-handler.tsx, GUI/src/util/percentage.ts
Related to:
- https://github.com/buerokratt/Analytics-Module/issues/169
=> The sector diagram shows wrong information

GUI/src/RootComponent.tsx, GUI/src/hoc/with-authorization.tsx, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/BurokrattPage/index.tsx, GUI/src/pages/ChatsPage/index.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/pages/OverviewPage.tsx, GUI/src/pages/ReportsPage.tsx
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/547
=> A user can access parts that he has no rights to

GUI/.env.development, GUI/.env.example, GUI/src/components/ChatsTable/index.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/resources/api-constants.ts, docker-compose.yml
Related to:
- https://github.com/buerokratt/Analytics-Module/issues/212
Combined with:
- https://github.com/buerokratt/Buerokratt-Chatbot/pull/649
=> BUG FIX - Can't view the conversations with negative feedback in the analytics module feedback section

GUI/src/components/MetricsCharts/index.tsx, GUI/src/components/OpenData/APISetupDrawer/index.tsx, GUI/src/components/OpenData/DatasetCreation/index.tsx, GUI/src/components/overview/MainMetricsArea/index.tsx, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/pages/OverviewPage.tsx, GUI/src/pages/ReportsPage.tsx, GUI/src/util/api-response-handler.tsx
- Added Credentials with requests
=> Hot fix requests cookie

DSL/Liquibase/changelog/1674138939-create-reorder-preferences-trigger.sql
- Fixed Create Reorder Preferences
=> Hot Fix Liquibase

DSL/Ruuter/GET/.guard, DSL/Ruuter/POST/.guard, DSL/Ruuter/TEMPLATES/check-user-authority.yml
=> Hot Fix UnAuthorized Status

GUI/src/pages/OverviewPage.tsx
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/642
=> Changes in the Analytics module

GUI/package.json, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/643
=> Update menu package version

GUI/src/components/context/ToastContext.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/710
=> Pop up messages fix

GUI/package.json, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json
Related to:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/721
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/710
=> Update header package version

DSL/Resql/feedback-avg-feedback-to-buerokratt-chats.sql, DSL/Resql/overview-avg-chats-no-csa.sql, DSL/Resql/overview-total-chats-no-csa.sql
- changes to feedback query conditions
=> Bürokrat statistics are not shown properly in the analytics module (#313)

DSL/Resql/feedback-selected-csa-feedback-nps.sql
Related tasks:
- https://github.com/buerokratt/Analytics-Module/issues/341
=> Fix CSA name on Selected CSA feedback chart

DSL/Resql/feedback-avg-feedback-to-buerokratt-chats.sql
Related task:
- https://github.com/buerokratt/Analytics-Module/issues/343
=> Fix feedback to Bürokratt chart

GUI/src/components/BarGraph/index.tsx, GUI/src/util/charts-utils.tsx, GUI/src/util/percentage.ts
Related task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/945
=> Fix zero values on charts

GUI/src/components/ChartToolTip/index.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json
Related tasks:
- https://github.com/buerokratt/Analytics-Module/issues/338
=> Fix translations in pie chart tooltip

GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/FeedbackPage.tsx, docker-compose.yml
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/340
=> Enhancement in Analytics module Negative feedback chats

GUI/src/pages/OverviewPage.tsx
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/348
=> Analytics module legend colors

GUI/src/hooks/usePeriodStatistics.ts
Related task:
- https://github.com/buerokratt/Analytics-Module/issues/328
=> Fix median values on chart

DSL/Resql/csa-avg-chat-time.sql, DSL/Resql/csa-chats-count.sql, DSL/Resql/feedback-selected-csa-feedback-nps.sql, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/FeedbackPage.tsx
- Updated Feedback view names
- Updated csa view names
- Updated related SQL' files
Related [task](https://github.com/buerokratt/Analytics-Module/issues/355).
=> Updated name display for filter with sql scritps.

DSL/Resql/get-user-page-preferences.sql, DSL/Resql/update-user-page-preferences.sql, DSL/Ruuter/GET/accounts/get-page-preference.yml, DSL/Ruuter/POST/accounts/update-page-preference.yml, GUI/src/pages/FeedbackPage.tsx
- Added sql to get page preferences
- Added dsl to get page preferences
- Added sql to save page preferences
- Added dsl to save page preferences
- Added flag to trigger preferences load
Related [task](https://github.com/buerokratt/Buerokratt-Chatbot/issues/1095).
=> 1095 page preference

GUI/src/hooks/usePeriodStatistics.ts, docker-compose.yml
Related task: https://github.com/buerokratt/DataMapper/issues/114
=> Add rate limit environment variable

GUI/src/components/ChatEvent/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1062
=> Hyperlink Support

GUI/.env.development, GUI/src/components/MetricAndPeriodOptions/OptionsPanel/index.tsx, GUI/src/components/MetricAndPeriodOptions/SubOptionsGroup/index.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/FeedbackPage.tsx
- Updated suboptions component to display selection 
Related [task](https://github.com/buerokratt/Analytics-Module/issues/363).
=> 363 quick select all

GUI/src/components/ChatEvent/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1134
=> Enhance Markdown Parsing

GUI/package.json
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1121
=> Human in the loop GUI enhancement

docker-compose.yml
Related Task:
- https://github.com/buerokratt/TIM/issues/37
=> Hot Fix: Docker Image Build 

GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/util/generateRandomColor.ts
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/397
=> Analytics module feedback CSA colors

DSL/Resql/overview-total-forwarded-chats.sql, GUI/src/i18n/et/common.json
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/388
=> Hot-Fix: Overview module incorrect directed chats count

GUI/src/components/ChatEvent/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1191
=> Encoding/decoding symbols in LLM messages

DSL/Resql/analytics/POST/feedback-buerokratt-chats-nps.sql, DSL/Resql/analytics/POST/feedback-chats-distribution.sql, DSL/Ruuter/analytics/POST/feedbacks/buerokratt-chats-distribution.yml, DSL/Ruuter/analytics/POST/feedbacks/buerokratt-chats-nps.yml, DSL/Ruuter/analytics/POST/feedbacks/csa-chats-distribution.yml, GUI/src/components/MetricsCharts/index.tsx, GUI/src/components/context/PeriodStatisticsContext.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/FeedbackPage.tsx, GUI/src/resources/api-constants.ts, GUI/src/types/chart.ts
Improve feedback pie chart.
This PR is related to issue https://github.com/buerokratt/Analytics-Module/issues/410
=> Improve feedback pie chart

GUI/src/components/FormElements/FormRadios/FormRadios.scss, GUI/src/components/FormElements/FormRadios/index.tsx, GUI/src/components/FormElements/index.tsx, GUI/src/components/MetricAndPeriodOptions/OptionsPanel/index.tsx, GUI/src/components/MetricsCharts/index.tsx, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/FeedbackPage.tsx, GUI/src/types/chart.ts
Improve Bürokratt conversations feedback graph.
This PR is related to issue https://github.com/buerokratt/Analytics-Module/issues/422
=> Improve Bürokratt conversations feedback graph

GUI/package.json, GUI/src/components/services/api.ts, GUI/src/components/services/mock-apis.ts, GUI/src/util/axios-client.ts
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1231
=> Hot-Fix: Browsers reading 300 responses from disk cache

DSL/Resql/analytics/POST/chat-count-only-chatbot.sql, DSL/Resql/analytics/POST/chat-count-with-csa.sql
- Update fetching NON CSA conversations for Analytics
- Update fetching CSA conversations for Aalytics.
- Updated criteria is TAKEN-OVER event which means CSA is being involved directly into conversation.
Related [task](https://github.com/buerokratt/Analytics-Module/issues/406).
=> Added checking for chatbot conversations

DSL/Resql/analytics/POST/status-all-chats.sql, DSL/Resql/analytics/POST/status-csa-chats.sql, GUI/src/i18n/en/common.json, GUI/src/i18n/et/common.json, GUI/src/pages/AdvisorsPage.tsx, GUI/src/pages/FeedbackPage.tsx, GUI/src/types/advisor.ts, GUI/src/util/charts-utils.tsx
Related task: https://github.com/buerokratt/Analytics-Module/issues/413
=> 413: Fix ended statuses chart

GUI/src/components/BarGraph/index.tsx, GUI/src/components/CustomChartTooltip/CustomChartTooltip.scss, GUI/src/components/CustomChartTooltip/index.tsx, GUI/src/components/LineGraph/index.tsx, GUI/src/components/context/PeriodStatisticsContext.tsx, GUI/src/components/index.tsx
Improve CSA graph.
This PR is related to issue https://github.com/buerokratt/Analytics-Module/issues/423
=> Improve CSA graph

GUI/src/components/MetricsCharts/MetricsCharts.scss, GUI/src/components/MetricsCharts/index.tsx
- Added graph wrapper to ensure proper height settings.
Related [task](https://github.com/buerokratt/Analytics-Module/issues/439).
=> 439 Legend styling

GUI/src/components/MetricsCharts/index.tsx
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/462
=> Hot-Fix: Download xlsx for chat feedback

DSL/Resql/analytics/POST/feedback-avg-feedback-to-buerokratt-chats.sql, DSL/Resql/analytics/POST/feedback-buerokratt-chats-nps.sql
Related Bug:
- https://github.com/buerokratt/Analytics-Module/issues/422#issuecomment-2782851351
=> Bug-Feedback-avg-nps

DSL/Resql/analytics/POST/chat-cif-outside-working-hours.sql
- Updated SQL
Related [task](https://github.com/buerokratt/Analytics-Module/issues/407).
=> 407 Contact information

DSL/Resql/analytics/POST/chat-count-with-csa-and-chatbot.sql
- Updated SQL to properly display total count.
Related [task](https://github.com/buerokratt/Analytics-Module/issues/406).
=> Added conditions to properly count the total amount.

GUI/src/pages/AdvisorsPage.tsx, GUI/src/util/charts-utils.tsx
- Added config equals check and applied it to template
Related [task](https://github.com/buerokratt/Analytics-Module/issues/474).
=> 474 Advisors page flickering

DSL/Resql/analytics/POST/overview-avg-chats-no-csa.sql, DSL/Resql/analytics/POST/overview-avg-chats.sql, DSL/Resql/analytics/POST/overview-avg-waiting-time.sql, DSL/Resql/analytics/POST/overview-chat-activity-chart.sql, DSL/Resql/analytics/POST/overview-total-chats-no-csa.sql, DSL/Resql/analytics/POST/overview-total-forwarded-chats.sql, GUI/src/pages/OverviewPage.tsx
Related Task:
- https://github.com/buerokratt/Analytics-Module/issues/477
=> Fix: analytics/overview/metrics should always use ended date

GUI/src/components/ChatEvent/Markdownify.tsx
Related Task:
- https://github.com/buerokratt/Chat-Widget/issues/443
=> Visual Changes For Markdownify

GUI/package.json, GUI/src/components/context/ToastContext.tsx, GUI/src/constants/const.ts
- Extracted duration to const.
- Set value to 5 seconds.
Related [task](https://github.com/buerokratt/Buerokratt-Chatbot/issues/1325).
=> 1325 Popup duration

GUI/package.json
- Updated package to v 0.0.20
Related [task](https://github.com/buerokratt/Training-Module/issues/965).
=> Updated package for common template to v 0.0.20

DSL/Ruuter/analytics/POST/agents/chats/avg-time.yml, DSL/Ruuter/analytics/POST/agents/chats/ended.yml, DSL/Ruuter/analytics/POST/agents/chats/total.yml, DSL/Ruuter/analytics/POST/chats/status.yml, DSL/Ruuter/analytics/POST/feedbacks/agents/nps.yml, DSL/Ruuter/analytics/POST/odp/dataset.yml, DSL/Ruuter/analytics/POST/odp/download.yml, DSL/Ruuter/analytics/POST/odp/update-scheduled-report.yml, DSL/Ruuter/analytics/POST/overview/preferences.yml, DSL/Ruuter/analytics/TEMPLATES/check-user-authority.yml, GUI/package.json
Related Task:
- https://github.com/buerokratt/Buerokratt-Chatbot/issues/1408
=> Fix: Hide sensitive information in history chat
